---
#:registry: "/opt/flockd/etc/registry.yml"
#:values: "/opt/flockd/etc/values.yml"
#:report_dir: "/opt/flockd/etc/reports"
#:hook_dir: "/opt/flockd/etc/hooks",
#:trigger_dir: "/opt/flockd/etc/triggers"
#:log_file: /var/log/flockd/flockd.log
:password: 'changeme-to-local-password'
:name: 'mycluster'
:hub: false
:hub_endpoint_url: http://localhost:9292/
